- name: Ensure /export/backup directory exists
  file: 
    path: /export/backup
    state: directory 
    
- name: Mount mountpoints
  mount: 
    path: /export/backup
    src: mango:/archive
    fstype: nfs 
    opts: defaults,nfsvers=4
    passno: 2 
    state: present
    
- name: Ensure directory exists
  file:
    path: "/home/{{ item }}/webdav"
    state: directory 
    mode: 700
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items:
    - sascha
    
- name: Mount mountpoints
  mount: 
    path: "/home/{{ item }}/webdav"
    src: "http://mango:90/remote.php/dav/files/{{ item }}/"
    fstype: davfs
    opts: "user,auto,rw,uid={{ item }},gid={{ item }},_netdev"
    state: present
  with_items:
    - sascha
    
