- name: add nginx apt-key
  apt_key: 
    url: "{{ item }}"
    state: present 
  loop:
    - https://download.opensuse.org/repositories/home:ungoogled_chromium/Debian_Buster/Release.key

- name: Add repos 
  apt_repository:
    repo: "{{ item }}"
    codename: bionic
    update_cache: true
    state: present
  loop:
    - ppa:unit193/encryption
    - deb http://download.opensuse.org/repositories/home:/ungoogled_chromium/Debian_Buster/ /

- name: Install packages
  apt: 
    name: "{{packages}}"
  vars:
    packages:
    - rsync
    - keepassxc
    - nfs-kernel-server
    - nfs-common
    - davfs2
    - ca-certificates
    - veracrypt
    - thunderbird
    - enigmail
    - scdaemon
    - restic
    - inkscape
    - nextcloud-desktop
    - filezilla
    - ungoogled-chromium
    - chromium-sandbox
